from langchain_core.tools import tool
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'kdump_analyze')))
from main import kdump_analysis

from typing import Annotated

@tool
def execute_gdb_command(
    gdb_command: str
)-> Annotated[dict, "Output of the gdb command"]:
    """
    Execute a GDB command to analyze kernel dump (vmcore) via kdump-gdbserver.
    
    This tool connects to kdump-gdbserver which loads the vmcore file, and has the
    vmlinux kernel image loaded. It can be used to:
    - Extract runtime information from the crash dump (registers, memory, stack traces)
    - Query kernel symbols and structures from the vmlinux image
    - Execute any standard GDB commands (info, x, bt, print, etc.)
    - Run kernel-specific GDB commands (e.g., lx-dmesg, lx-symbols)

    Args:
        gdb_command (str): The GDB command to execute (e.g., "info registers", "bt", "x/10x 0xffffffff81000000")
        
    Returns:
        dict: A dictionary containing:
            - 'result' (str): 'success' if command executed successfully, 'error' if failed
            - 'output' (list): List of output strings if successful, or error messages if failed
            
        Example success: {'result': 'success', 'output': ['rax = 0x1234', 'rbx = 0x5678']}
        Example error: {'result': 'error', 'output': ['Invalid address']}
    """
    try:
        output = kdump_analysis.execute(gdb_command)
        return output
    except Exception as e:
        return {'result': 'error', 'output': [f"Error executing gdb command: {str(e)}"]}
    
@tool
def getCrashReport() -> Annotated[str, "Crash report from kdump-gdbserver"]:
    """
    Get the crash report from kdump-gdbserver.
    
    This tool retrieves the crash report generated by kdump-gdbserver after analyzing the vmcore.
    
    Returns:
        str: The crash report as a string, or an error message if retrieval fails.
    """
    try:
        status, report = kdump_analysis.getCrashReport()
        if not status:
            err = "Sorry, failed to retrieve crash report. Because: " + report
            return err
        return report
    except Exception as e:
        return f"Error retrieving crash report: {str(e)}"