from __future__ import annotations

import os
import json
import sys
from io import StringIO
from pathlib import Path
from re import sub

from dotenv import dotenv_values, load_dotenv


ENV_KEYS = [
    "API_KEY",
    "MODEL_NAME",
    "MODEL_PROVIDER",
    "LLM_BASE_URL",
    "TAVILY_API_KEY",
    "LANGFUSE_SECRET_KEY",
    "LANGFUSE_PUBLIC_KEY",
    "LANGFUSE_HOST",
    "PAGEINDEX_API_KEY",
    "OPENAI_API_KEY",
    "OPENAI_API_BASE",
    "DEEPSEEK_API_KEY",
    "MODEL_TEMPERATURE",
    "SHELL_TOOL_WORKSPACE_ROOT",
]


def get_settings_path() -> Path:
    configured = os.getenv("AGENT4KDUMP_CLIENT_SETTINGS")
    if configured:
        return Path(configured).expanduser().resolve()
    return (Path.cwd() / "cache/client_settings.json").resolve()


def read_settings() -> dict:
    path = get_settings_path()
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def write_settings(settings: dict) -> None:
    path = get_settings_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(settings, ensure_ascii=False, indent=2), encoding="utf-8")


def get_env_path() -> Path:
    configured = os.getenv("AGENT4KDUMP_ENV_PATH")
    if configured:
        return Path(configured).expanduser().resolve()
    stored = read_settings().get("env_path")
    if stored:
        return Path(str(stored)).expanduser().resolve()
    return (Path.cwd() / ".env").resolve()


def get_bundled_env_path() -> Path | None:
    roots: list[Path] = []
    pyinstaller_root = getattr(sys, "_MEIPASS", None)
    if pyinstaller_root:
        roots.append(Path(pyinstaller_root))
    roots.extend([Path(__file__).resolve().parents[2], Path.cwd()])
    for root in roots:
        candidate = (root / ".env").resolve()
        if candidate.exists():
            return candidate
    return None


def load_client_env() -> None:
    bundled = get_bundled_env_path()
    if bundled:
        load_dotenv(bundled, override=False)
    path = get_env_path()
    if path.exists():
        load_dotenv(path, override=True)


def read_env_values() -> dict[str, str]:
    values: dict[str, str] = {}
    bundled = get_bundled_env_path()
    if bundled:
        values.update(
            {
                key: str(value)
                for key, value in dotenv_values(bundled).items()
                if key in ENV_KEYS and value is not None
            }
        )
    path = get_env_path()
    if path.exists():
        values.update(
            {
                key: str(value)
                for key, value in dotenv_values(path).items()
                if key in ENV_KEYS and value is not None
            }
        )
    return values


def mask_value(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:2]}{'*' * max(len(value) - 6, 4)}{value[-4:]}"


def is_sensitive_key(key: str) -> bool:
    upper = key.upper()
    return any(marker in upper for marker in ["KEY", "SECRET", "TOKEN", "PASSWORD"])


def env_status() -> dict:
    values = read_env_values()
    return {
        "path": str(get_env_path()),
        "values": {
            key: {
                "configured": bool(values.get(key)),
                "masked": mask_value(values.get(key, "")),
                "value": (
                    mask_value(values.get(key, ""))
                    if is_sensitive_key(key)
                    else values.get(key, "")
                ),
                "sensitive": is_sensitive_key(key),
            }
            for key in ENV_KEYS
        },
    }


def write_env_values(updates: dict[str, str | None]) -> dict:
    path = get_env_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    current = read_env_values()

    for key, value in updates.items():
        if key not in ENV_KEYS:
            continue
        if value is None:
            current.pop(key, None)
        else:
            current[key] = value.strip()

    lines = [
        "# Generated by agent4kdump client.",
        "# Empty values are allowed; use the Settings page to update this file.",
        "",
    ]
    for key in ENV_KEYS:
        if key in current:
            escaped = current[key].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    load_client_env()
    return env_status()


def load_existing_env_file(path_value: str) -> dict:
    path = Path(path_value).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f".env file does not exist: {path}")

    # Validate that python-dotenv can parse the file before switching the client.
    dotenv_values(path)
    settings = read_settings()
    settings["env_path"] = str(path)
    write_settings(settings)
    os.environ["AGENT4KDUMP_ENV_PATH"] = str(path)
    load_client_env()
    return env_status()


def import_env_file(filename: str | None, content: str) -> dict:
    dotenv_values(stream=StringIO(content))
    safe_name = sub(r"[^A-Za-z0-9._-]+", "_", filename or ".env").strip("._") or "env"
    if not safe_name.endswith(".env"):
        safe_name = f"{safe_name}.env"

    target_dir = (Path.cwd() / "cache/client_env").resolve()
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = (target_dir / safe_name).resolve()
    if target_dir not in target_path.parents:
        raise ValueError("Invalid .env import target path.")

    target_path.write_text(content, encoding="utf-8")
    return load_existing_env_file(str(target_path))
