[package]
name = "agent4kdump_complete_client"
version = "0.1.0"
description = "Desktop client for agent4kdump"
authors = ["agent4kdump"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = ["dialog-open", "shell-open"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
