"""Compatibility wrapper for legacy imports.

Prompt definitions are split into:
- agents/search_prompt.py
- agents/analyze_prompt.py
"""

from agents.search_prompt import SEARCH_PROMPT, ENHANCE_PROMPT, COT_PROMPT, TEST_PROMPT
from agents.analyze_prompt import (
    ANALYZE_OBJECT_PROMPT,
    ANALYZE_TAINT_PROMPT,
    ANALYZE_ROOT_PROMPT,
    ANALYZE_WORKFLOW_SYSTEM_PROMPT,
    TEST_ANALYZE_OBJECT_PROMPT,
    TEST_ANALYZE_TAINT_PROMPT,
    TEST_ANALYZE_ROOT_PROMPT,
    TEST_ANALYZE_WORKFLOW_PROMPT,
)

# Backward-compatible aliases for legacy imports.
ANALYZE_PROMPT = ANALYZE_ROOT_PROMPT
TEST_ANALYZE_PROMPT = TEST_ANALYZE_ROOT_PROMPT

__all__ = [
    "SEARCH_PROMPT",
    "ANALYZE_PROMPT",
    "ANALYZE_OBJECT_PROMPT",
    "ANALYZE_TAINT_PROMPT",
    "ANALYZE_ROOT_PROMPT",
    "ANALYZE_WORKFLOW_SYSTEM_PROMPT",
    "ENHANCE_PROMPT",
    "COT_PROMPT",
    "TEST_PROMPT",
    "TEST_ANALYZE_PROMPT",
    "TEST_ANALYZE_OBJECT_PROMPT",
    "TEST_ANALYZE_TAINT_PROMPT",
    "TEST_ANALYZE_ROOT_PROMPT",
    "TEST_ANALYZE_WORKFLOW_PROMPT",
]
