from .commandTools import ALLOWED_COMMANDS

from typing import Annotated
import shlex
from .tool_timeout import timed_tool

# Global variable to hold the kdump_analysis instance
_KDUMP_ANALYSIS_INSTANCE = None

def set_kdump_analysis_instance(instance):
    """Set the global kdump_analysis instance."""
    global _KDUMP_ANALYSIS_INSTANCE
    _KDUMP_ANALYSIS_INSTANCE = instance

def get_kdump_analysis_instance():
    """Get the global kdump_analysis instance."""
    if _KDUMP_ANALYSIS_INSTANCE is None:
        raise RuntimeError("kdump_analysis instance not set. Call set_kdump_analysis_instance() first.")
    return _KDUMP_ANALYSIS_INSTANCE

# Dangerous GDB commands that should be blocked
DANGEROUS_GDB_COMMANDS = [
    '!',           # Shell escape - can execute arbitrary system commands
    'shell',       # Execute shell commands
    'run',         # Run the program (not applicable for vmcore but still dangerous)
    'start',       # Start program execution
    'continue',    # Continue execution
    'attach',      # Attach to another process
    'detach',      # Detach from process
    'quit',        # Exit GDB
    'q',           # Quit shorthand
]

SHELL_CONTROL_OPERATORS = (';', '|', '&', '>', '<', '`', '$', '(', ')', '{', '}', '\n')


def _is_safe_shell_command(shell_cmd: str) -> bool:
    """
    Allow only simple single-command shell invocations that start with an allowlisted binary.
    """
    if not shell_cmd:
        return False

    if any(token in shell_cmd for token in SHELL_CONTROL_OPERATORS):
        return False

    try:
        parts = shlex.split(shell_cmd)
    except ValueError:
        return False

    if not parts:
        return False

    return parts[0] in ALLOWED_COMMANDS

def filter_gdb_command(command: str) -> bool:
    """
    Filter the command to ensure it is safe to execute in GDB.
    
    Blocks dangerous commands that could:
    - Execute arbitrary shell commands (!, shell)
    - Modify system state or files
    - Exit the GDB session
    - Execute only allowed shell commands from ALLOWED_COMMANDS
    
    Args:
        command (str): The GDB command to filter.
        
    Returns:
        bool: True if the command is allowed, False otherwise.
    """
    command = command.strip()

    if not command:
        return False
    
    # Extract the first word (the actual command)
    first_word = command.split()[0].lower()
    
    # Block dangerous GDB commands with special handling for shell escapes
    if first_word in DANGEROUS_GDB_COMMANDS:

        if first_word in ('!', 'shell'):
            # Extract the shell command
            if first_word == '!':
                shell_cmd = command[1:].strip()
            else: 
                shell_cmd = ' '.join(command.split()[1:]).strip()

            return _is_safe_shell_command(shell_cmd)
        
        # Block all other dangerous commands
        return False

    return True
    

@timed_tool(
    timeout_seconds=20,
    timeout_factory=lambda name, sec: {
        "result": "error",
        "output": [f"Tool '{name}' timed out after {sec} seconds."],
    },
)
def execute_gdb_command(
    gdb_command: Annotated[str, "The GDB command to execute (e.g., 'info registers', 'bt')"]
)-> Annotated[dict, "Output of the gdb command"]:
    """
    Execute a GDB command to analyze kernel dump (vmcore) via kdump-gdbserver.
    
    This tool connects to kdump-gdbserver which loads the vmcore file, and has the
    vmlinux kernel image loaded. It can be used to:
    - Extract runtime information from the crash dump (registers, memory, stack traces)
    - Query kernel symbols and structures from the vmlinux image
    - Execute any standard GDB commands (info, x, bt, print, etc.)
    - Run kernel-specific GDB commands (e.g., lx-dmesg, lx-symbols)

    Example success: {'result': 'success', 'output': ['rax = 0x1234', 'rbx = 0x5678']}
    Example error: {'result': 'error', 'output': ['Invalid address']}
    """
    try:
        # Filter dangerous commands before execution
        if not filter_gdb_command(gdb_command):
            return {
                'result': 'error',
                'output': [f"Command blocked for safety: '{gdb_command}'. Dangerous commands (shell escape, quit, etc.) are not allowed."]
            }
        
        output = get_kdump_analysis_instance().execute(gdb_command)
        return output
    except Exception as e:
        return {'result': 'error', 'output': [f"Error executing gdb command: {str(e)}"]}
    
@timed_tool(timeout_seconds=30)
def getCrashReport() -> Annotated[str, "Crash report from kdump-gdbserver"]:
    """
    Get the crash report from kdump-gdbserver.
    
    This tool retrieves the crash report generated by kdump-gdbserver after analyzing the vmcore.
    """
    try:
        status, report = get_kdump_analysis_instance().getCrashReport()
        if not status:
            err = "Sorry, failed to retrieve crash report. Because: " + report
            return err
        return report
    except Exception as e:
        return f"Error retrieving crash report: {str(e)}"
